services:

  backend:
    build: ./backend
    image: elanssarioumaima/soghani-chatbot-backend:latest
    container_name: soghani-chatbot-backend
    ports:
      - "8000:5000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FLASK_ENV=production
      - PORT=5000
    restart: always
    networks:
      - soghani-network

  frontend:
    build: ./frontend
    image: elanssarioumaima/soghani-frontend:latest
    container_name: soghani-frontend
    ports:
      - "8001:80"
    restart: always
    networks:
      - soghani-network
    depends_on:
      - backend
      - server

  server:
    build: ./server
    image: elanssarioumaima/soghani-server:latest
    container_name: soghani-server
    ports:
      - "8002:4000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - PORT=4000
    restart: always
    networks:
      - soghani-network

networks:
  soghani-network:
    driver: bridge